---
- name: create a hosts file
  hosts: all
  become: true
  tasks:
    - name: create a file
      ansible.builtin.template:
        src: ./hosts.j2
        dest: /etc/myhosts

- name: delete file
  hosts: all, !dev
  become: true
  tasks:
    - name: delete file
      ansible.builtin.file:
        path: /etc/myhosts
        state: absent